name: opengs-slam
channels:
  - pytorch
  - nvidia
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aom=3.9.1
  - blas=1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.7.4
  - cairo=1.18.0
  - certifi=2024.7.4
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.5.39
  - cuda-runtime=12.1.0
  - cuda-version=12.5
  - dav1d=1.2.1
  - expat=2.6.2
  - ffmpeg=7.0.1
  - filelock=3.15.4
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - fribidi=1.0.10
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - gmp=6.3.0
  - gmpy2=2.1.5
  - gnutls=3.7.9
  - graphite2=1.3.13
  - h2=4.1.0
  - harfbuzz=9.0.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - icu=75.1
  - idna=3.7
  - intel-openmp=2022.0.1
  - jinja2=3.1.4
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20240116.2
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libass=0.17.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.10.1.7
  - libcurand=10.3.6.82
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.20
  - libdrm=2.4.122
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgcc-ng=14.1.0
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libglib=2.80.3
  - libgomp=14.1.0
  - libhwloc=2.11.1
  - libiconv=1.17
  - libidn2=2.3.7
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libnpp=12.0.2.50
  - libnsl=2.0.1
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libopenvino=2024.2.0
  - libopenvino-auto-batch-plugin=2024.2.0
  - libopenvino-auto-plugin=2024.2.0
  - libopenvino-hetero-plugin=2024.2.0
  - libopenvino-intel-cpu-plugin=2024.2.0
  - libopenvino-intel-gpu-plugin=2024.2.0
  - libopenvino-intel-npu-plugin=2024.2.0
  - libopenvino-ir-frontend=2024.2.0
  - libopenvino-onnx-frontend=2024.2.0
  - libopenvino-paddle-frontend=2024.2.0
  - libopenvino-pytorch-frontend=2024.2.0
  - libopenvino-tensorflow-frontend=2024.2.0
  - libopenvino-tensorflow-lite-frontend=2024.2.0
  - libopus=1.3.1
  - libpciaccess=0.18
  - libpng=1.6.43
  - libprotobuf=4.25.3
  - libsqlite=3.46.0
  - libstdcxx-ng=14.1.0
  - libtasn1=4.19.0
  - libtiff=4.6.0
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libva=2.22.0
  - libvpx=1.14.1
  - libwebp-base=1.4.0
  - libxcb=1.16
  - libxcrypt=4.4.36
  - libxml2=2.12.7
  - libzlib=1.3.1
  - llvm-openmp=15.0.7
  - markupsafe=2.1.5
  - mkl=2022.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.5
  - nettle=3.9.1
  - networkx=3.3
  - ocl-icd=2.3.2
  - openh264=2.4.1
  - openjpeg=2.5.2
  - openssl=3.3.1
  - p11-kit=0.24.1
  - pcre2=10.44
  - pillow=10.4.0
  - pip=24.0
  - pixman=0.43.2
  - plyfile=1.0.3
  - pthread-stubs=0.4
  - pugixml=1.14
  - pycparser=2.22
  - pysocks=1.7.1
  - python=3.11.9
  - python_abi=3.11
  - pytorch=2.1.0
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.1
  - readline=8.2
  - requests=2.32.3
  - setuptools=71.0.4
  - snappy=1.2.1
  - svt-av1=2.1.2
  - sympy=1.13.0
  - tbb=2021.12.0
  - tk=8.6.13
  - torchaudio=2.1.0
  - torchtriton=2.1.0
  - torchvision=0.16.0
  - tqdm=4.66.4
  - typing_extensions=4.12.2
  - urllib3=2.2.2
  - wayland=1.23.0
  - wayland-protocols=1.36
  - wheel=0.43.0
  - x264=1!164.3095
  - x265=3.5
  - xorg-fixesproto=5.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxrender=0.9.11
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - yaml=0.2.5
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - absl-py==2.1.0
      - addict==2.4.0
      - aiofiles==23.2.1
      - annotated-types==0.7.0
      - anyio==4.4.0
      - argcomplete==3.4.0
      - asttokens==2.4.1
      - attrs==23.2.0
      - blinker==1.8.2
      - bracex==2.4
      - build==1.2.1
      - clarabel==0.9.0
      - click==8.1.7
      - comm==0.2.2
      - configargparse==1.7
      - contourpy==1.2.1
      - cvxpy==1.5.2
      - cycler==0.12.1
      - dash==2.17.1
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - decorator==5.1.1
      - dnspython==2.6.1
      - docker-pycreds==0.4.0
      - ecos==2.0.14
      - einops==0.8.0
      - email-validator==2.2.0
      - evo==1.11.0
      - executing==2.0.1
      - fastapi==0.111.1
      - fastapi-cli==0.0.4
      - fastjsonschema==2.20.0
      - ffmpy==0.3.2
      - flask==3.0.3
      - fonttools==4.53.1
      - freetype-py==2.4.0
      - fsspec==2024.6.1
      - gitdb==4.0.11
      - gitpython==3.1.43
      - glfw==2.7.0
      - gradio==4.39.0
      - gradio-client==1.1.1
      - grpcio==1.65.1
      - h11==0.14.0
      - httpcore==1.0.5
      - httptools==0.6.1
      - httpx==0.27.0
      - huggingface-hub==0.24.2
      - imageio==2.34.2
      - imgviz==1.7.5
      - importlib-metadata==8.2.0
      - importlib-resources==6.4.0
      - ipython==8.26.0
      - ipywidgets==8.1.3
      - itsdangerous==2.2.0
      - jedi==0.19.1
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter-core==5.7.2
      - jupyterlab-widgets==3.0.11
      - kapture==1.1.10
      - kapture-localization==1.1.10
      - kiwisolver==1.4.5
      - lightning-utilities==0.11.6
      - llvmlite==0.43.0
      - lpips==0.1.4
      - lz4==4.3.3
      - markdown==3.6
      - markdown-it-py==3.0.0
      - matplotlib==3.5.3
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - munch==4.0.0
      - natsort==8.4.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - numba==0.60.0
      - numexpr==2.10.1
      - numpy==1.26.4
      - numpy-quaternion==2023.0.4
      - open3d==0.18.0
      - opencv-python==4.8.1.78
      - orjson==3.10.6
      - osqp==0.6.7.post1
      - packaging==24.1
      - pandas==2.2.2
      - parso==0.8.4
      - pexpect==4.9.0
      - piexif==1.1.3
      - pillow-heif==0.18.0
      - platformdirs==4.2.2
      - plotly==5.23.0
      - poselib==2.0.2
      - prompt-toolkit==3.0.47
      - protobuf==4.25.4
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycolmap==3.10.0
      - pydantic==2.8.2
      - pydantic-core==2.20.1
      - pydub==0.25.1
      - pyglet==1.5.29
      - pyglm==2.7.1
      - pygments==2.18.0
      - pyopengl==3.1.0
      - pyparsing==3.1.2
      - pyproject-hooks==1.1.0
      - pyquaternion==0.9.9
      - pyrender==0.1.45
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-multipart==0.0.9
      - pytz==2024.1
      - qdldl==0.1.7.post4
      - referencing==0.35.1
      - retrying==1.3.4
      - rich==13.7.1
      - roma==1.5.0
      - rosbags==0.10.4
      - rpds-py==0.19.1
      - ruamel-yaml==0.18.6
      - ruamel-yaml-clib==0.2.8
      - ruff==0.5.5
      - safetensors==0.4.3
      - scikit-learn==1.5.1
      - scipy==1.14.0
      - scs==3.2.6
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - sentry-sdk==2.11.0
      - setproctitle==1.3.3
      - shellingham==1.5.4
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - stack-data==0.6.3
      - starlette==0.37.2
      - tabulate==0.9.0
      - tenacity==8.5.0
      - tensorboard==2.17.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.5.0
      - tomlkit==0.12.0
      - torchmetrics==1.4.0.post0
      - traitlets==5.14.3
      - trimesh==4.4.3
      - typer==0.12.3
      - tzdata==2024.1
      - uvicorn==0.30.3
      - uvloop==0.19.0
      - wandb==0.17.5
      - watchfiles==0.22.0
      - wcmatch==8.5.2
      - wcwidth==0.2.13
      - websockets==11.0.3
      - werkzeug==3.0.3
      - widgetsnbextension==4.0.11
      - zipp==3.19.2
      - submodules/simple-knn
      - submodules/diff-gaussian-rasterization
